language:
  ruby

rvm:
  - '1.9'
  - '2.0'
  - '2.1'
  - '2.2'
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

  fast_finish:
    true

script:
  rake test

install:
  - gem install nuggets power_assert

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev
